webgriffe_sylius_table_rate_plugin_shipping_table_rate:
  resource: |
    alias: webgriffe.shipping_table_rate
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: webgriffe_sylius_table_rate_plugin_shipping_table_rate
    vars:
      all:
        subheader: webgriffe_sylius_table_rate_plugin.ui.shipping_table_rates.subheader
      index:
        icon: 'pallet'
  type: sylius.resource
