services:
    Webgriffe\SyliusTableRateShippingPlugin\Calculator\TableRateShippingCalculator:
        arguments:
            - '@webgriffe.repository.shipping_table_rate'
        tags:
            -
                name: sylius.shipping_calculator
                calculator: !php/const Webgriffe\SyliusTableRateShippingPlugin\Calculator\TableRateShippingCalculator::TYPE
                label: 'Table rate'
