services:
    Webgriffe\SyliusTableRateShippingPlugin\Calculator\TableRateShippingCalculator:
        arguments:
            - '@webgriffe.repository.shipping_table_rate'
        tags:
            -
                name: sylius.shipping_calculator
                calculator: !php/const Webgriffe\SyliusTableRateShippingPlugin\Calculator\TableRateShippingCalculator::TYPE
                label: 'Table rate'

    Webgriffe\SyliusTableRateShippingPlugin\Checker\TableRateShippingMethodEligibilityChecker:
        decorates: sylius.shipping_eligibility_checker
        arguments:
            - '@Webgriffe\SyliusTableRateShippingPlugin\Checker\TableRateShippingMethodEligibilityChecker.inner'
            - '@Webgriffe\SyliusTableRateShippingPlugin\Calculator\TableRateShippingCalculator'

    Webgriffe\SyliusTableRateShippingPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
